services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_PASSWORD}
    volumes:
      - seq_data:/data

volumes:
  seq_data:
